services:
  memcached:
    image: memcached
    restart: always
    expose:
      - "11211"
  yopass:
    image: buisecrets
    restart: always
    ports:
      - "127.0.0.1:1337:1337" 
    command: "--memcached=memcached:11211 --port 1337"
    depends_on:
      - memcached